class_name ProgressionBalance
extends RefCounted

const OFFLINE_BASE_CAP_HOURS := 12
const OFFLINE_SUBSCRIBER_CAP_HOURS := 16
const OFFLINE_MIN_POPUP_SECONDS := 900
const OFFLINE_BASE_GOLD_PER_HOUR := 120
const OFFLINE_GOLD_PER_REGION := 25
const OFFLINE_GOLD_PER_STAGE := 8
const OFFLINE_GOLD_PER_LEVEL := 3
const OFFLINE_BASE_EXP_PER_HOUR := 18
const OFFLINE_EXP_PER_REGION := 4
const OFFLINE_EXP_PER_STAGE := 1
const OFFLINE_EXP_PER_LEVEL := 1
